### ISSUE TITLE
Make sure we don't serialise accidentally in Shelley

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-base#101]
The new Shelley annotations allow for serialise-by-annotation using the standard `ToCBOR` class. However, this opens the possibility that we accidentally serialise something. We could avoid this by subclassing `ToCBOR` with something like `ToCBORViaAnnotation`. The implementation would be the same, but using this as a constraint would help us find places where we might accidentally be serialising.

**Comment by dcoutts** [comment]
In particular we should use this for the functions for hashing and sig verification.

**Comment by redxaxder** [comment]
Is the error you're anticipating one where we don't annotate something and it is used as if it was annotated?

**Comment by lehins** [comment]
All types require hashing of their original bytes are backed by `MemoBytes` in ledger, which avoids the reserialization. In other words this is not a concern of serialization library. Also signing now uses `getSignableRepresentation`, instead of `serialize`, so this is no longer an issue.
