### ISSUE TITLE
KES implementation

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-base#102]
This is the tracking ticket for the KES crypto implementation to be used in Praos.

Needed for https://github.com/input-output-hk/ouroboros-network/issues/261.

For those able to access it, the requirement discussion is here https://jira.iohk.io/browse/CDT-60

The algorithm we have chosen is the iterated sum construction from the MMM paper https://eprint.iacr.org/2001/034, section 3.1. The specific parameter is to allow 2^7 key evolutions, since that allows for the required 90 days limit, at one evolution per day (or more precisely the equivalent in slots).

This design choice has been reviewed by the Ouroboros Praos authors.

The implementation choice is a direct implementation of the construction in C, on top of the existing signature scheme we use elsewhere.

The strategy to integrate is to implement a Haskell FFI binding to the KES C code and use that binding library to instantiate the existing crypto class being used by consensus.

Tasks
- [ ] establish and check the feasibility of the relationship between the C API and the target Haskell API
- [ ] select underlying signature implementation
- [ ] implement C code
- [ ] initial FFI binding
- [ ] match up against the target KES type class
- [ ] make any necessary changes to the KES type class and uses
- [ ] first working integration
- [ ] tests
- [ ] `memlock` safety
- [ ] audit of the C code

**Comment by kevinhammond** [comment]
@vincenthz  has very kindly offered us this KES implementation in C (with a Haskell binding), produced by translation from C.  This would save us effort, especially as Vincent has significant expertise.  Please could @tdammers and @nc6 evaluate this for use in the Haskell node.

https://github.com/input-output-hk/kes-mmm-sumed25519
