### ISSUE TITLE
Implement `mlock` safety for VRF FFI bindings

### ISSUE THREAD

**Issue by tdammers** [input-output-hk/cardano-base#112]
Make VRF FFI bindings as developed in #110 `mlock`-safe.

Outline:

- Introduce Haskell wrappers for the C types that represent messages and keys
- Couple `mlock` / `munlock` C calls to the creation and finalization of those types

**Comment by dcoutts** [comment]
We now believe we do not need mlock safety for the VRF keys, only for the KES keys.

**Comment by tdammers** [comment]
OK, closing. We'll reopen if this turns out to be necessary after all.
