### ISSUE TITLE
`libsodiumInit` needs to be called

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-base#175]
It would be nice if we didn't need to call `libsodiumInit` directly when using libsodium based crypto. For example in `cardano-node`: https://github.com/input-output-hk/cardano-node/pull/1958/files#diff-af911e411955f9dc3a3b1ba96132e67830dd2322ac98d6c90071c5b30b224b00R18

**Comment by lehins** [comment]
There is no way around not initializing libsodium, it must be done at least once before libsodium based functionality can be used. Same applies to the secp256k1 librray. That is why we now provide this function that can be called instead that will take care of all of the crypto initialization:
https://github.com/input-output-hk/cardano-base/blob/a344b32d97b0d0e83b773069f6a20f7e5fa67478/cardano-crypto-class/src/Cardano/Crypto/Init.hs#L25
