### ISSUE TITLE
nix-shell fails on master

### ISSUE THREAD

**Issue by kozross** [input-output-hk/cardano-base#301]
```
[koz@Sebastian cardano-base]$ nix-shell
trace: Not using IOHK default nixpkgs (use 'niv drop nixpkgs' to use default for better sharing)
error: Unknown index-state 2022-08-15T00:00:00Z, the latest index-state I know about is 2022-03-03T00:00:00Z. You may need to update to a newer hackage.nix.
(use '--show-trace' to show detailed location information)
```

This has been an issue since at least [this commit](https://github.com/input-output-hk/cardano-base/commit/278e71d44ad2a347992449a08e5de72a6672c0d7).

**Comment by iquerejeta** [comment]
@lehins , @newhoggy, any idea what could be happening here? Thanks 🙏

**Comment by lehins** [comment]
@iquerejeta I have no idea. If you could approve [this PR](https://github.com/input-output-hk/cardano-base/pull/300) that reverts the PR that broke nix-shell then we can unblock master at least. 

There is some WIP in https://github.com/input-output-hk/cardano-base/pull/298 but I have no idea about the status of it. Maybe @hamishmack can shed some light on it.

**Comment by iquerejeta** [comment]
Ah, great. Thanks. I don't really understand what was the motivation of doing those index state changes, so I don't feel quite confortable approving to revert. I think its better if we have the approval by @newhoggy or @hamishmack .

**Comment by newhoggy** [comment]
I've verified that @hamishmack 's commit fixes `nix-shell`.

**Comment by iquerejeta** [comment]
I'm closing this as `nix-shell` now works properly.

**Comment by iquerejeta** [comment]
I'm closing this as `nix-shell` now works properly.
