### ISSUE TITLE
Secp256k1 new built ins

### ISSUE THREAD

**Issue by vfrsilva** [input-output-hk/cardano-base#304]
### Business Hypothesis
SECP256K1 is an elliptic curve used in Bitcoin and Ethereum.
We want to enable our Plutus language with signature verification over this curve so that dapp developers can use it to create cross-chain applications, bridges and side chains. This is a strategic development that will increase adoption and make it possible to implement wrapped assets in the Cardano network. In particular, we are including the ECDSA and Schnorr signature verification algorithms

### Drivers
- Adoption
- Devx
- Cross blockchain communication

### Functional Requirements
- SECP256 C library is integrated into Plutus
- dapp developers can use SECP256 primitives as a built-in function in Plutus
- The built-in interface follows the one defined in the CIP
- It should be available only in major protocol version 8

### Risks
Testing exposes some further vulnerabilities. Low risk

### External Dependencies
- SECP library implementors to implement the library in the proper way following guidance from IOHK Crypto team
- Security Audit by Internal/external teams
- Plutus team
- Automate the SECP256K1 tests  in the E2E testing framework. 

### DoD
- Major protocol version is equal to 8
- Cost model is updated to allow execution of the primitive
- Audit has no security concerns
- SECP256K1 primitive can be used as a Plutus built-in function

**Comment by iquerejeta** [comment]
Code already implemented in #252 , #258, #262 and #289. Still finalising some testing before closing this.

**Comment by iquerejeta** [comment]
Closed in #320
