### ISSUE TITLE
Error in nix-shell, missing blst dependency

### ISSUE THREAD

**Issue by iquerejeta** [input-output-hk/cardano-base#331]
Error when trying to run the BLS12-381 branch with nix. 
```
trace: Not using IOHK default nixpkgs (use 'niv drop nixpkgs' to use default for better sharing)
building '/nix/store/qxgj384y8xwjhl082rg7ash8sx8d7dl9-git-ls-files.drv'...
error: The Nixpkgs package set does not contain the package: blst (system dependency).
       You may need to augment the system package mapping in haskell.nix so that it can be found.```

_Originally posted by @arthurgreef in https://github.com/input-output-hk/cardano-base/issues/266#issuecomment-1295971577_

**Comment by zypeh** [comment]
@iquerejeta Is there any pointer for me to try to add the extra dependencies to nix. Just faced the same issue but not sure where to edit the nix files.

**Comment by iquerejeta** [comment]
Ah! Forgot about this issue. [This](https://github.com/input-output-hk/cardano-base/commit/6d2474f600bba0bf7f6bfe96f7da8523a8f97c4c#diff-b9a0014cf6c4615d1c2e8d921dc3db59b4a68b462788d667ed622331660d17cdL40) should have fixed it. If it still does not work, please open a new issue. Thanks!
