### ISSUE TITLE
Experiment including rust dependencies to cardano-base

### ISSUE THREAD

**Issue by iquerejeta** [input-output-hk/cardano-base#346]
The idea is to try and replace the two functions that rely on cryptonite (SHA3 and Keccak) with a rust alternative, using [cabal-pack](https://crates.io/crates/cabal-pack). 

Initially,  intention of merging this to master, but rather serve as a discovering phase of how easy it is to bind rust code to our codebase.

**Comment by lehins** [comment]
@iquerejeta Is it really worth it? Do we have some Rust library that we actually need to bind to? If not, then I'd suggest we shouldn't spend valuable resources on hypothetical problems. 

With respect to SHA3 and Keccak, I don't see any problem of continuing using cryptonite for those.

Do you mind if I close this ticket?
