### ISSUE TITLE
Use lazy bytestrings for annotations

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/cardano-base#57]
Is there a particular reason for using strict bytestrings as annotations?

In https://github.com/input-output-hk/ouroboros-network/issues/1215 we argue for switching to lazy bytestrings as that would decrease the amount of copying required when deserialising blocks.

@redxaxder

**Comment by lehins** [comment]
Closing this ticket as no longer relevant. See more info on the reasons in my comment on th e linked ouroboros ticket: https://github.com/input-output-hk/ouroboros-network/issues/1215#issuecomment-1524319812
