### ISSUE TITLE
Packages aren't licensed properly

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-base#72]
They should be following https://input-output.atlassian.net/wiki/spaces/EN/pages/819757219/Open-Source+License

This has actual annoying consequences: the various `x2nix` tools carry over the license metadata, and assume that these packages are therefore unfree, which requires some additional fussing to allow them. It would be simpler if they were just licensed properly!

**Comment by erikd** [comment]
PR?

**Comment by michaelpj** [comment]
I had 10 minutes so I made an issue. Perhaps if nobody else does anything I'll make a PR in a bit ;)
